### ISSUE TITLE
Running HASTEN with other docking software

### ISSUE THREAD

**Issue by Tonylac77** [TuomoKalliokoski/HASTEN#1]
Hi,

I am wondering if it possible to run HASTEN with my own consensus docking pipeline. If so, could you provide some instructions on how to do this?

Many thanks and congratulations for this work,

Tony

**Comment by TuomoKalliokoski** [comment]
Hello Tony and thanks for the kind words!

If your consensus docking pipeline takes molecules in SMILES as the input and outputs single numeric docking score value to rank them then this should be pretty straightforward. However, if you would like to use the different docking methods in your consensus docking pipeline as a multiple inputs for ML instead of just single docking score value then I am afraid that the current tool is too limited for that as it is built around optimizing single value only.

Assuming that your consensus docking pipeline produces single value per SMILES: first solution that comes to my mind is that you operate HASTEN like your consensus docking pipeline is just like Glide. In your case, glide_tutorial.in could contain whatever (just use the tutorial glide_tutorial.in).

It would go something like this:

1. Create HASTEN db: python3 hasten.py -a import-smiles -m tutorial.db -s tutorial.smi
2. Pick iteration 1 compounds: python3 hasten.py -a pick -m tutorial.db -i 1 -n vs -f 0.01 -c 16 -d glide_tutorial.in
3. This would create three types of files: vs_iter1_cpu*.smi which contain the molecules to dock and some other files that you can ignore (".inp" files and ".in", those are for Schrödinger tools). Now just run these *.smi files through to your docking pipeline (you'll probably need a script here).
4. After the docking, write a script to process your docking output to produce ","-delimited CSV file that has a header line with two columns: "title" (the compound ID from input SMILES) and "r_i_docking_score" (your docking score: smaller value, the better). These files must be named like "glide_vs_iter1_cpu*.csv".
5. Import the CSV normally: python3 hasten.py -a import-dock -m tutorial.db -i 1 -n vs
6. Continue the tutorial normally.

Obviously the pose export functionality doesn't work with other tools than Schrödinger (you'll have to dig them out yourself for visualization).

Also note that I have no experience on how well does the ML part of HASTEN (chemprop) predict consensus docking scores compared to the single program docking scores. That would require some additional studies, but the above should get you started on that path.

Best regards,
Tuomo

**Comment by Tonylac77** [comment]
Thanks for the detailed and quick answer. I will certainly give it a go!
