### ISSUE TITLE
Phase Database

### ISSUE THREAD

**Issue by smoes-prime** [TuomoKalliokoski/HASTEN#4]
Hi Tuomo,
I am having some issues with my version of Phase, which made me wonder what is the purpose of creating a phase database? It seems like an extra step when all we need is the output from ligprep. What is the benefit compared to the old version which went straight from ligprep into glide?

All the best,
Sebastian

**Comment by TuomoKalliokoski** [comment]
Hello Sebastian,

The benefit of using Phase is that it is less limited by the Schrödinger license. If you don't have such constraints from the license then you can use LigPrep instead of Phase and it is indeed more straightforward that way (an example script glide_confgen.sh can be found within the original HASTEN version).

Best regards,
Tuomo
